### ISSUE TITLE
Runtime error when attempt to run the wiki

### ISSUE THREAD

**Issue by oren** [GoWiki/GoWiki#3]
```
go get
go build
./GoWiki

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4bfb6d]

goroutine 1 [running]:
net/http.(*Server).Serve(0xc82001e720, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1884 +0x40d
main.main()
        /home/oren/projects/go/src/github.com/oren/GoWiki/main.go:59 +0x17c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

```

I am on Ubuntu 14.04, go version: go1.5.2 linux/amd64

**Comment by andyleap** [comment]
Most likely it's due to GoWiki listening on port 3000 conflicting with something.  I've added an error message for that case, and added a flag to specify port to listen on `./GoWiki -port 4000` or so
